spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://34.101.202.112:5432/devBank
    username: bankDev
    password: bankDev
    driver-class-name: org.postgresql.Driver
  transaction:
    default-timeout: 10000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresPlusDialect
    hibernate:
      ddl-auto: update
    format-sql: true
server:
  port: 8081
  servlet:
    context-path: /bank-transaction-system

